// <auto-generated />
using System;
using ASP_P42.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_P42.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_P42.Data.Entities.UserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccess");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96dcbbba-9aee-44a2-8835-72dfe4e1a710"),
                            Dk = "FCB57CECE720632FDBB68958CF953E46",
                            Login = "Admin",
                            RoleId = new Guid("21f7c25a-629b-4beb-9339-0c37ac9a8444"),
                            Salt = "96DCBBBA-9AEE-44A2-8835-72DFE4E1A710",
                            UserId = new Guid("190052ca-f844-498a-a05f-1d4ba2adc0e8")
                        });
                });

            modelBuilder.Entity("ASP_P42.Data.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UsersData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("190052ca-f844-498a-a05f-1d4ba2adc0e8"),
                            BirthDate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "CHANGE@ME",
                            FullName = "Адміністратор Системи",
                            Phone = "CHANGE_ME",
                            RegisteredAt = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ASP_P42.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreateLevel")
                        .HasColumnType("int");

                    b.Property<int>("DeleteLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadLevel")
                        .HasColumnType("int");

                    b.Property<int>("UpdateLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsersRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21f7c25a-629b-4beb-9339-0c37ac9a8444"),
                            CreateLevel = 10,
                            DeleteLevel = 10,
                            Description = "Корневой администратор",
                            Name = "Admin",
                            ReadLevel = 10,
                            UpdateLevel = 10
                        },
                        new
                        {
                            Id = new Guid("c741df27-da81-4d54-b61b-c4c9a2ae7a73"),
                            CreateLevel = 0,
                            DeleteLevel = 0,
                            Description = "Самозарегистрировавшийся пошльзователь",
                            Name = "User",
                            ReadLevel = 0,
                            UpdateLevel = 0
                        });
                });

            modelBuilder.Entity("ASP_P42.Data.Entities.UserAccess", b =>
                {
                    b.HasOne("ASP_P42.Data.Entities.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_P42.Data.Entities.UserData", "UserData")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("ASP_P42.Data.Entities.UserData", b =>
                {
                    b.Navigation("Accesses");
                });
#pragma warning restore 612, 618
        }
    }
}
